name: on-promise-cicd
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Set Tags Name'
        required: true
        default: main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.set-version.outputs.VERSION_NAME }}
    steps:
      - id: set-version # v1.0.0 -> v1-0-0
        run: |
          echo "VERSION_NAME=$(echo "${{github.event.inputs.tags }}" | sed "s/\./\-/g")" >> $GITHUB_OUTPUT

      - name: Check Version Name
        run: |
          echo "Check Version ${{ steps.set-version.outputs.VERSION_NAME }}"

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.tags }}'

      - name: Grant execute permission for gradlew
        run: chmod +x boot-app/gradlew

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Gradlew
        working-directory: boot-app
        run: ./gradlew clean test bootJar

      - name: Add version
        working-directory: boot-app
        run: |
          mv build/libs/cicd-0.0.1-SNAPSHOT.jar build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd-study-application #cicd-study-application.zip runner에 upload
          path: boot-app/build/libs/cicd-study-${{ steps.set-version.outputs.VERSION_NAME }}.jar
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4 # Job 끼리는 파일을 공유할 수 없으므로(runner 가 다름) 업로드하고 다운로드하는 방식
        with:
          name: cicd-study-application
          path: boot-app/build/libs/

      - name: Deploy to EC2 # app.log 2>&1 에러로그, 정상로그 모두 app.log 로 쌓이게 함
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no boot-app/build/libs/cicd-study-${{ needs.build.outputs.release }}.jar ${{ secrets.EC2_USER_NAME}}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER_NAME}}/cicd-study-${{ needs.build.outputs.release }}.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME}}@${{ secrets.EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.EC2_USER_NAME}}/cicd-study-${{ needs.build.outputs.release }}.jar > app.log 2>&1 &"
          rm -f private_key.pem

